/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
}
export type BlogPostId = bigint;
export type Category = { 'caballeros' : null } |
  { 'ninos' : null } |
  { 'damas' : null };
export interface Product {
  'imagePath' : string,
  'name' : string,
  'referenceCode' : string,
  'category' : Category,
  'price' : string,
}
export type ProductId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string], BlogPostId>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPost' : ActorMethod<[BlogPostId], BlogPost>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'updateBlogPost' : ActorMethod<[BlogPostId, BlogPost], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];