/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPostId = IDL.Nat;
export const Category = IDL.Variant({
  'caballeros' : IDL.Null,
  'ninos' : IDL.Null,
  'damas' : IDL.Null,
});
export const Product = IDL.Record({
  'imagePath' : IDL.Text,
  'name' : IDL.Text,
  'referenceCode' : IDL.Text,
  'category' : Category,
  'price' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BlogPostId], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPostId = IDL.Nat;
  const Category = IDL.Variant({
    'caballeros' : IDL.Null,
    'ninos' : IDL.Null,
    'damas' : IDL.Null,
  });
  const Product = IDL.Record({
    'imagePath' : IDL.Text,
    'name' : IDL.Text,
    'referenceCode' : IDL.Text,
    'category' : Category,
    'price' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BlogPostId], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };